stages:
  data_ingestion:
    cmd: python src\house_reg\pipelines\stage_01_data_ingestion.py
        
    deps:
      - src\house_reg\pipelines\stage_01_data_ingestion.py
      - config\config.yaml
    
    outs:
      - artifacts\data_ingestion\data.zip

    
  prepare_train_model:
    cmd : python src\house_reg\pipelines\stage_02_prepare_train_model.py

    deps:
      - src\house_reg\pipelines\stage_02_prepare_train_model.py
      - config\config.yaml

    outs:
      - artifacts\prepare_base_model\model.pkl

  model_evaluation:
    cmd:  python src\house_reg\pipelines\stage_03_model_evaluation.py

    deps:
      - src\house_reg\pipelines\stage_03_model_evaluation.py
      - config\config.yaml

    metrics:
      - scores.json:
          cache: false
